SELECT 
  ED.ID,
  COALESCE(J.CHILD_COUNT,0) AS CHILD_COUNT
FROM ECOLI_DATA ED
LEFT JOIN (
    SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
) J
    ON ED.ID = J.PARENT_ID
ORDER BY ED.ID;

    
