-- 코드를 입력하세요
SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, J.SCORE
FROM REST_INFO RI
JOIN (
    select REST_ID, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
) J
ON RI.REST_ID = J.REST_ID
WHERE SUBSTRING(RI.ADDRESS,1,2)='서울'
ORDER BY J.SCORE DESC, RI.FAVORITES DESC;
