WITH RECURSIVE HOURS AS(
    SELECT 0 AS H
    UNION ALL
    SELECT 
    H+1
    FROM HOURS
    WHERE H<23
), CNT AS (
    SELECT HOUR(DATETIME) AS H, COUNT(*) AS C
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
)
SELECT HOURS.H AS HOUR, IFNULL(CNT.C, 0) AS COUNT
FROM HOURS
LEFT JOIN CNT ON CNT.H=HOURS.H
ORDER BY HOURS.H;
