SELECT ID, B.FISH_NAME, LENGTH
FROM (
    SELECT A.*,
           ROW_NUMBER() OVER (
               PARTITION BY A.FISH_TYPE
               ORDER BY A.LENGTH DESC, A.ID ASC
           ) AS rn
    FROM FISH_INFO A
) t
JOIN FISH_NAME_INFO B ON t.FISH_TYPE = B.FISH_TYPE
WHERE rn = 1
ORDER BY ID;
