SELECT B.SCORE, B.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
FROM HR_EMPLOYEES A
JOIN (
    SELECT SUM(SCORE) AS SCORE, EMP_NO
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SCORE DESC
    LIMIT 1
) B ON A.EMP_NO=B.EMP_NO
JOIN HR_DEPARTMENT C ON A.DEPT_ID=C.DEPT_ID 