-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(A.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN (
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE DATE_FORMAT(SALES_DATE,'%Y-%m')='2022-01'
    GROUP BY BOOK_ID
) A
ON B.BOOK_ID=A.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC