WITH masks AS (
  SELECT
    MAX(CASE WHEN NAME = 'Python' THEN CODE END) AS PY,
    MAX(CASE WHEN NAME = 'C#' THEN CODE END)    AS C,
    BIT_OR(CASE WHEN CATEGORY = 'Back End'  THEN CODE ELSE 0 END) AS BE_MASK,
    BIT_OR(CASE WHEN CATEGORY = 'Front End' THEN CODE ELSE 0 END) AS FE_MASK
  FROM SKILLCODES
)
SELECT
  CASE
    WHEN (D.SKILL_CODE & M.PY) != 0 AND (D.SKILL_CODE & M.FE_MASK) != 0 THEN 'A'
    WHEN (D.SKILL_CODE & M.C) != 0 THEN 'B'
    WHEN (D.SKILL_CODE & M.FE_MASK) != 0 THEN 'C'
  END AS GRADE,
  D.ID,
  D.EMAIL
FROM DEVELOPERS D
CROSS JOIN masks M
WHERE
  ((D.SKILL_CODE & M.PY) != 0 AND (D.SKILL_CODE & M.FE_MASK) != 0)
  OR ((D.SKILL_CODE & M.C) != 0)
  OR ((D.SKILL_CODE & M.FE_MASK) != 0)
ORDER BY GRADE ASC, ID ASC;
